# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'WatchCuts' do

pod 'CorePlot', '~> 2.0'

end

target 'WatchCuts WatchKit App' do

end

target 'WatchCuts WatchKit Extension' do

end

